### ISSUE TITLE
register package

### ISSUE THREAD

**Issue by gszep** [gszep/FluxContinuation#11]

**Comment by gszep** [comment]
@JuliaRegistrator register

**Comment by gszep** [comment]
@JuliaRegistrator register

**Comment by gszep** [comment]
@JuliaRegistrator register

**Comment by gszep** [comment]
@JuliaRegistrator register

**Comment by gszep** [comment]
@JuliaRegistrator register

**Comment by gszep** [comment]
@JuliaRegistrator register

**Comment by gszep** [comment]
@JuliaRegistrator register

**Comment by rveltz** [comment]
Hey,

Are you sure you want to do this? BK has changed a lot in the mean time.

please also consider moving it to the gh org bifurcatiokit

**Comment by gszep** [comment]
Hi @rveltz ! Thank you for reaching out :) well all the of unit tests I created are passing? I would appreciate if you can find any bugs in the [diff between the two versions](https://github.com/gszep/BifurcationInference.jl/compare/v0.1.3...v0.1.4). Happy to move this project to the org you mention. I can initiate the transfer now

**Comment by gszep** [comment]
I do not have permissions to create repos on the `bifurcationkit` org. You would have to add me as a member with certain privileges before I can initiate transfer. I would also appreciate retaining admin rights to `BifurcationInference.jl` 😄

**Comment by rveltz** [comment]
The diff is massive but I congratulate because that was not simple work. I am impressed

**Comment by rveltz** [comment]
>  I would also appreciate retaining admin rights to BifurcationInference.jl

Sure, if I mess up, I will give it back to you :D

**Comment by rveltz** [comment]
I sent you an invit

**Comment by gszep** [comment]
I think the diff is only massive because I had an automatic formatter on CTRL+S haha

**Comment by rveltz** [comment]
Do you have enough rights on the org?

**Comment by rveltz** [comment]
Thank you for joining!

You have admin rights to your own repo :D
I will try to find a better way because you are only collaborator. If you are a member with admin right, you would have admin rights to all repo, I am not sure how to change this granularity
