### ISSUE TITLE
symbolic complexity of analytical forms

### ISSUE THREAD

**Issue by gszep** [gszep/FluxContinuation#6]
Currently we are using Mathematica scripts to evaluate the determinant of jacobian, its curvature and the integration region velocity, then copying the code to Julia. More complex models yield symbolic complexity where it is no longer feasible to do so.

![Screenshot from 2020-07-20 09-18-56](https://user-images.githubusercontent.com/17977117/87910533-76669580-ca6a-11ea-8e38-2852948b7587.png)

We would like an autodiff way - ideally using `Zygote.jl` of computing the following 
![Screenshot from 2020-07-20 09-26-02](https://user-images.githubusercontent.com/17977117/87910954-23d9a900-ca6b-11ea-984a-03ffde77dc14.png)
![Screenshot from 2020-07-20 09-25-51](https://user-images.githubusercontent.com/17977117/87910955-24723f80-ca6b-11ea-8f10-867aea74394a.png)

**Comment by ndalchau** [comment]
Check this out: https://github.com/JuliaInterop/MathLink.jl

**Comment by gszep** [comment]
now implemented using pure autodiff
